/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.ControleurPanelFormulaire;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modele.BoutonDate;
import modele.Date;

/**
 *
 * @author miste
 */
public class PanelCalendrierDate extends javax.swing.JPanel {

    /**
     * Creates new form PanelCalendrierDate
     */
    public PanelCalendrierDate() {
        initComponents();
        initPanelCalendrier(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelNavigation = new javax.swing.JPanel();
        labelIndicationMois = new javax.swing.JLabel();
        boutonMoisPrecedent = new javax.swing.JButton();
        boutonMoisSuivant = new javax.swing.JButton();
        panelCalendrier = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 120, 215));
        setPreferredSize(new java.awt.Dimension(100, 100));

        panelNavigation.setBackground(java.awt.Color.white);
        panelNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 215)));

        labelIndicationMois.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        labelIndicationMois.setText("Juin 2020");

        boutonMoisPrecedent.setBackground(java.awt.Color.white);
        boutonMoisPrecedent.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        boutonMoisPrecedent.setText("<");
        boutonMoisPrecedent.setBorder(null);
        boutonMoisPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMoisPrecedentActionPerformed(evt);
            }
        });

        boutonMoisSuivant.setBackground(java.awt.Color.white);
        boutonMoisSuivant.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        boutonMoisSuivant.setText(">");
        boutonMoisSuivant.setBorder(null);
        boutonMoisSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMoisSuivantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavigationLayout = new javax.swing.GroupLayout(panelNavigation);
        panelNavigation.setLayout(panelNavigationLayout);
        panelNavigationLayout.setHorizontalGroup(
                panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNavigationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelIndicationMois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 551, Short.MAX_VALUE)
                                .addComponent(boutonMoisPrecedent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boutonMoisSuivant)
                                .addContainerGap())
        );
        panelNavigationLayout.setVerticalGroup(
                panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNavigationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelIndicationMois)
                                        .addComponent(boutonMoisSuivant)
                                        .addComponent(boutonMoisPrecedent))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        String[] JOUR_DE_LA_SEMAINE = {"lu.", "ma.", "me.", "je.", "ve.", "sa.", "di."};
        javax.swing.JLabel[] labelJourSemaine = new javax.swing.JLabel[JOUR_DE_LA_SEMAINE.length];
        for (int i = 0; i < labelJourSemaine.length; i++) {
            labelJourSemaine[i] = new javax.swing.JLabel(JOUR_DE_LA_SEMAINE[i]);
            labelJourSemaine[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            panelCalendrier.add(labelJourSemaine[i]);
        }
        for (int i = 0; i < listeBoutonDate.length; i++){
            listeBoutonDate[i] = new BoutonDate(new Date());
            listeBoutonDate[i].setBorder(null);
            listeBoutonDate[i].setFocusPainted(false);
            panelCalendrier.add(listeBoutonDate[i]);
        }
        panelCalendrier.setBackground(java.awt.Color.white);
        panelCalendrier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 215)));
        panelCalendrier.setLayout(new java.awt.GridLayout(7, 7));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelCalendrier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelCalendrier, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void initPanelCalendrier(Date date){
        Date dateTemp = date;
        dateReperage = date;
        labelIndicationMois.setText(date.toStringMoisAnnee());
        while(dateTemp.getJour() != 1){
            dateTemp = dateTemp.dateDeLaVeille();
        }
        while(dateTemp.getJourSemaine() != 2){
            dateTemp = dateTemp.dateDeLaVeille();
        }

        for (int i = 0; i < listeBoutonDate.length; i++){
            listeBoutonDate[i].setText(dateTemp.toStringJour());
            listeBoutonDate[i].setDate(dateTemp);
            listeBoutonDate[i].setBackground(Color.WHITE);
            listeBoutonDate[i].setForeground(Color.BLACK);
            listeBoutonDate[i].setBorder(null);
            if (dateTemp.getMois() != date.getMois()){
                listeBoutonDate[i].setForeground(Color.LIGHT_GRAY);
            }
            if (dateTemp.compareTo(new Date()) == 0){
                listeBoutonDate[i].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 120, 215)));
            }
            if (dateSelectionnee == null){
                dateSelectionnee = new Date();
            }
            if (dateTemp.compareTo(dateSelectionnee) == 0){
                listeBoutonDate[i].setForeground(Color.WHITE);
                listeBoutonDate[i].setBackground(new Color(0,120,215));
            }
            dateTemp = dateTemp.dateDuLendemain();
        }
    }

    public void enregistreEcouteur(ControleurPanelFormulaire controleurPanelFormulaire){
        for (int i = 0; i < listeBoutonDate.length; i++){
            listeBoutonDate[i].addActionListener(controleurPanelFormulaire);
        }
    }

    public void setDate(Date date){
        dateSelectionnee = date;
        initPanelCalendrier(date);
    }

    public Date getDateSelectionnee(){
        return dateSelectionnee;
    }

    public BoutonDate[] getListeBoutonDate(){
        return listeBoutonDate;
    }

    public JButton getBoutonMoisPrecedent(){
        return boutonMoisPrecedent;
    }

    public JButton getBoutonMoisSuivant(){
        return boutonMoisSuivant;
    }

    private void boutonMoisPrecedentActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        initPanelCalendrier(dateReperage.moisPrecedent());
    }

    private void boutonMoisSuivantActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        initPanelCalendrier(dateReperage.moisSuivant());
    }

    private BoutonDate[] listeBoutonDate = new BoutonDate[42];
    private Date dateSelectionnee;
    private Date dateReperage;
    // Variables declaration - do not modify
    private javax.swing.JButton boutonMoisPrecedent;
    private javax.swing.JButton boutonMoisSuivant;
    private javax.swing.JLabel labelIndicationMois;
    private javax.swing.JPanel panelCalendrier;
    private javax.swing.JPanel panelNavigation;
    // End of variables declaration
}
